# Generated by Django 4.0.4 on 2022-05-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_cliente_status_alter_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteVip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank='true', max_length=50, null='True')),
                ('apellido', models.CharField(blank='true', max_length=50, null='True')),
                ('edad', models.IntegerField(blank='true', null='True')),
                ('email', models.EmailField(blank='true', max_length=254, null='True', verbose_name='mail del cliente')),
                ('fecha_registro', models.DateField(blank='true', null='True')),
                ('fecha_nacimiento', models.DateField(blank='true', null='True')),
                ('clave', models.CharField(blank='true', max_length=8, null='True')),
                ('status', models.IntegerField(choices=[(1, 'Premium'), (2, 'VIP')], default=1)),
            ],
        ),
    ]
