# Generated by Django 4.0.3 on 2022-05-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={},
        ),
    ]
