# Generated by Django 4.0.3 on 2022-05-24 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0017_tienda_remove_proveedor_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tienda',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tienda'),
        ),
    ]
